### PR TITLE
Add in parsing of Custom Emojis entity to the main Status object

### PR DESCRIPTION
**Pull request by CodeBunTes**
I recently added in some support on H5YR.com to be able to bring through the custom emojis available on the umbracocommunity.social server, for when people post for example :umbracoheart: or :umbracopackage: . At the moment this is being done via a direct API call in the H5YR codebase, but rather than it just being isolated to there, I thought I'd submit it as a proper PR here if interested/useful so it can be available in the library I know most people in the Umbraco community are commonly using anyway.

Essentially it's a small change to add to the status model so it'll bring through the 'Emojis' field, complete with an extra model to map the Mastodon Custom Emoji entity for this collection. Devs using the library will then have access to the collection of custom emojis that go with each individual status if they want to do a text > img replacement of them on their front end render. I've tested it works against a local pull in of the #h5yr hashtag with the number of posts extended to 50 so as to get my post from January 15th pulled back (Seb is the only other person to have used one on this hashtag more recently, however he's on an external instance so it correctly doesn't bring them down for that post).

image

Have tried to match up all naming/coding standards as they appear on the existing models.

### CODE REVIEW

**Review by abjerner — APPROVED** [review]
Hi @CodeBunTes and thanks for your PR 👍 

There was an unused import, and the `GetBoolean` extension method doesn't need null value suppression as it returns `bool` and not `bool?`. But these are really minor, so I went ahead and fixed them.

The rest looks spot on 👍

**Comment by abjerner** [comment]
New release is here btw:

https://github.com/abjerner/Skybrud.Social.Mastodon/releases/tag/v1.0.0-alpha004

**Comment by CodeBunTes** [comment]
@abjerner Apologies for the delay in replying, but I only finally got round to pulling down the alpha004 release to use it this evening, and can't see the updates to the model showing in the new version. Has something possibly gotten missed off as I can see GitHub still marking 2 commits since the 004 release?

image

**Comment by abjerner** [comment]
@CodeBunTes you're absolutely right. Your changes unfortunately weren't included in the alpha004 release 🤦‍♂️ 

I normally pull down a PR first to test it locally, then delete it locally, and merge via GitHub. Somehow I hadn't pulled down the changes before creating the new release.

I've now pushed a alpha005 release with your PR as well as a number of other changes/improvements:

https://github.com/abjerner/Skybrud.Social.Mastodon/releases/tag/v1.0.0-alpha005

**Comment by CodeBunTes** [comment]
@abjerner Ah, I've lost count of the amount of times I've missed something out when working with Git, though with me it's usually forgetting to actually push something. I've pulled the newest alpha005 release down anyway and that all works great now. Many thanks!

**Pull request merged**
